// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sjVjhDwAwAnzPPjTJm6wuM
// Component: vPms2ampwPsR50
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_azure_landing_page_project.module.css"; // plasmic-import: sjVjhDwAwAnzPPjTJm6wuM/projectcss
import sty from "./PlasmicFathymFooter.module.css"; // plasmic-import: vPms2ampwPsR50/css

import TwitterIconIcon from "./icons/PlasmicIcon__TwitterIcon"; // plasmic-import: 6E0DD-0IRv50Gh/icon
import GithubIconIcon from "./icons/PlasmicIcon__GithubIcon"; // plasmic-import: nIQZpWDwYtcGUP/icon
import FacebookIconIcon from "./icons/PlasmicIcon__FacebookIcon"; // plasmic-import: Q-1wMdW2K9OR5W/icon

export type PlasmicFathymFooter__VariantMembers = {};

export type PlasmicFathymFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicFathymFooter__VariantsArgs;
export const PlasmicFathymFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicFathymFooter__ArgsType = {};
type ArgPropType = keyof PlasmicFathymFooter__ArgsType;
export const PlasmicFathymFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicFathymFooter__OverridesType = {
  root?: p.Flex<"div">;
  fathymFramework?: p.Flex<"a"> & Partial<LinkProps>;
  ioTEnsemble?: p.Flex<"a"> & Partial<LinkProps>;
  habistack?: p.Flex<"a"> & Partial<LinkProps>;
  docs?: p.Flex<"a"> & Partial<LinkProps>;
  blog?: p.Flex<"a"> & Partial<LinkProps>;
  support?: p.Flex<"a"> & Partial<LinkProps>;
  enterpriseAgreement?: p.Flex<"a"> & Partial<LinkProps>;
  termsOfService?: p.Flex<"a"> & Partial<LinkProps>;
  privacyPolicy?: p.Flex<"a"> & Partial<LinkProps>;
  httpstwittercomFathymIt?: p.Flex<"a"> & Partial<LinkProps>;
  httpsgithubcomfathym?: p.Flex<"a"> & Partial<LinkProps>;
  httpswwwfacebookcomFathymInc?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultFathymFooterProps {
  className?: string;
}

function PlasmicFathymFooter__RenderFunc(props: {
  variants: PlasmicFathymFooter__VariantsArgs;
  args: PlasmicFathymFooter__ArgsType;
  overrides: PlasmicFathymFooter__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__vDvQp)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__gPnfj)} />

        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__fhPpO)}
          displayHeight={"75px" as const}
          displayMaxHeight={"75%" as const}
          displayMaxWidth={"none" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"auto" as const}
          loading={"lazy" as const}
          src={{
            src: "/plasmic/azure_landing_page_project/images/fathymLogoAqua01400Pxlspng.png",
            fullWidth: 400,
            fullHeight: 129,
            aspectRatio: undefined
          }}
        />

        <div className={classNames(projectcss.all, sty.freeBox___8WULg)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__orRce)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__g3De7
              )}
            >
              {"Products"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"fathymFramework"}
              data-plasmic-override={overrides.fathymFramework}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.fathymFramework
              )}
              component={Link}
              href={"https://www.fathym.com/" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jdNiU
                )}
              >
                {"Fathym Platform"}
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"ioTEnsemble"}
              data-plasmic-override={overrides.ioTEnsemble}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.ioTEnsemble
              )}
              component={Link}
              href={"https://www.fathym.com/iot" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bTQdz
                )}
              >
                {"IoT Ensemble"}
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"habistack"}
              data-plasmic-override={overrides.habistack}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.habistack
              )}
              component={Link}
              href={"https://www.habistack.com/" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t3Hpn
                )}
              >
                {"Habistack"}
              </div>
            </p.PlasmicLink>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__tohEs)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8SwT
              )}
            >
              {"Resources"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"docs"}
              data-plasmic-override={overrides.docs}
              className={classNames(projectcss.all, projectcss.a, sty.docs)}
              component={Link}
              href={"https://www.fathym.com/docs/" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bq2V
                )}
              >
                {"Docs"}
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"blog"}
              data-plasmic-override={overrides.blog}
              className={classNames(projectcss.all, projectcss.a, sty.blog)}
              component={Link}
              href={"https://www.fathym.com/blog" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vQy3J
                )}
              >
                {"Blog"}
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"support"}
              data-plasmic-override={overrides.support}
              className={classNames(projectcss.all, projectcss.a, sty.support)}
              component={Link}
              href={"mailto:support@fathym.com" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__itVh2
                )}
              >
                {"Support"}
              </div>
            </p.PlasmicLink>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__srSEc)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ybdot
              )}
            >
              {"Company"}
            </div>

            <p.PlasmicLink
              data-plasmic-name={"enterpriseAgreement"}
              data-plasmic-override={overrides.enterpriseAgreement}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.enterpriseAgreement
              )}
              component={Link}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oXhMp
                )}
              >
                {"Enterprise Agreement"}
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"termsOfService"}
              data-plasmic-override={overrides.termsOfService}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.termsOfService
              )}
              component={Link}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hyik0
                )}
              >
                {"Terms of Service"}
              </div>
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"privacyPolicy"}
              data-plasmic-override={overrides.privacyPolicy}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.privacyPolicy
              )}
              component={Link}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ePrnL
                )}
              >
                {"Privacy Policy"}
              </div>
            </p.PlasmicLink>
          </p.Stack>
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__vs85Q)} />

        <div className={classNames(projectcss.all, sty.freeBox__wjGll)}>
          <div className={classNames(projectcss.all, sty.freeBox__hsGaf)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cg0Li
              )}
            >
              {"Copyright "}
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__guOz)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/azure_landing_page_project/images/copyrightIcon.png",
                fullWidth: 24,
                fullHeight: 24,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jtrOa
              )}
            >
              {" 2022 Fathym. All rights reserved."}
            </div>
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__iRWcR)}
          >
            <p.PlasmicLink
              data-plasmic-name={"httpstwittercomFathymIt"}
              data-plasmic-override={overrides.httpstwittercomFathymIt}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.httpstwittercomFathymIt
              )}
              component={Link}
              href={"https://twitter.com/FathymIt" as const}
              platform={"nextjs"}
            >
              <TwitterIconIcon
                className={classNames(projectcss.all, sty.svg__pLmo)}
                role={"img"}
              />
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpsgithubcomfathym"}
              data-plasmic-override={overrides.httpsgithubcomfathym}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.httpsgithubcomfathym
              )}
              component={Link}
              href={"https://github.com/fathym" as const}
              platform={"nextjs"}
            >
              <GithubIconIcon
                className={classNames(projectcss.all, sty.svg__kTyGz)}
                role={"img"}
              />
            </p.PlasmicLink>

            <p.PlasmicLink
              data-plasmic-name={"httpswwwfacebookcomFathymInc"}
              data-plasmic-override={overrides.httpswwwfacebookcomFathymInc}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.httpswwwfacebookcomFathymInc
              )}
              component={Link}
              href={"https://www.facebook.com/FathymInc/" as const}
              platform={"nextjs"}
            >
              <FacebookIconIcon
                className={classNames(projectcss.all, sty.svg__zcYjD)}
                role={"img"}
              />
            </p.PlasmicLink>
          </p.Stack>
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "fathymFramework",
    "ioTEnsemble",
    "habistack",
    "docs",
    "blog",
    "support",
    "enterpriseAgreement",
    "termsOfService",
    "privacyPolicy",
    "httpstwittercomFathymIt",
    "httpsgithubcomfathym",
    "httpswwwfacebookcomFathymInc"
  ],
  fathymFramework: ["fathymFramework"],
  ioTEnsemble: ["ioTEnsemble"],
  habistack: ["habistack"],
  docs: ["docs"],
  blog: ["blog"],
  support: ["support"],
  enterpriseAgreement: ["enterpriseAgreement"],
  termsOfService: ["termsOfService"],
  privacyPolicy: ["privacyPolicy"],
  httpstwittercomFathymIt: ["httpstwittercomFathymIt"],
  httpsgithubcomfathym: ["httpsgithubcomfathym"],
  httpswwwfacebookcomFathymInc: ["httpswwwfacebookcomFathymInc"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  fathymFramework: "a";
  ioTEnsemble: "a";
  habistack: "a";
  docs: "a";
  blog: "a";
  support: "a";
  enterpriseAgreement: "a";
  termsOfService: "a";
  privacyPolicy: "a";
  httpstwittercomFathymIt: "a";
  httpsgithubcomfathym: "a";
  httpswwwfacebookcomFathymInc: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFathymFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFathymFooter__VariantsArgs;
    args?: PlasmicFathymFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFathymFooter__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFathymFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFathymFooter__ArgProps,
          internalVariantPropNames: PlasmicFathymFooter__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicFathymFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFathymFooter";
  } else {
    func.displayName = `PlasmicFathymFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFathymFooter = Object.assign(
  // Top-level PlasmicFathymFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    fathymFramework: makeNodeComponent("fathymFramework"),
    ioTEnsemble: makeNodeComponent("ioTEnsemble"),
    habistack: makeNodeComponent("habistack"),
    docs: makeNodeComponent("docs"),
    blog: makeNodeComponent("blog"),
    support: makeNodeComponent("support"),
    enterpriseAgreement: makeNodeComponent("enterpriseAgreement"),
    termsOfService: makeNodeComponent("termsOfService"),
    privacyPolicy: makeNodeComponent("privacyPolicy"),
    httpstwittercomFathymIt: makeNodeComponent("httpstwittercomFathymIt"),
    httpsgithubcomfathym: makeNodeComponent("httpsgithubcomfathym"),
    httpswwwfacebookcomFathymInc: makeNodeComponent(
      "httpswwwfacebookcomFathymInc"
    ),

    // Metadata about props expected for PlasmicFathymFooter
    internalVariantProps: PlasmicFathymFooter__VariantProps,
    internalArgProps: PlasmicFathymFooter__ArgProps
  }
);

export default PlasmicFathymFooter;
/* prettier-ignore-end */
