// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sjVjhDwAwAnzPPjTJm6wuM
// Component: 7mTzTuLk_-7aUm
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_azure_landing_page_project.module.css"; // plasmic-import: sjVjhDwAwAnzPPjTJm6wuM/projectcss
import sty from "./PlasmicValueProp.module.css"; // plasmic-import: 7mTzTuLk_-7aUm/css

export type PlasmicValueProp__VariantMembers = {
  flatIcon: "flatIcon";
  vertical: "vertical";
  card: "card";
  noTitle: "noTitle";
  darkBackground: "darkBackground";
};

export type PlasmicValueProp__VariantsArgs = {
  flatIcon?: SingleBooleanChoiceArg<"flatIcon">;
  vertical?: SingleBooleanChoiceArg<"vertical">;
  card?: SingleBooleanChoiceArg<"card">;
  noTitle?: SingleBooleanChoiceArg<"noTitle">;
  darkBackground?: SingleBooleanChoiceArg<"darkBackground">;
};

type VariantPropType = keyof PlasmicValueProp__VariantsArgs;
export const PlasmicValueProp__VariantProps = new Array<VariantPropType>(
  "flatIcon",
  "vertical",
  "card",
  "noTitle",
  "darkBackground"
);

export type PlasmicValueProp__ArgsType = {
  description?: React.ReactNode;
  icon?: React.ReactNode;
  title?: React.ReactNode;
};

type ArgPropType = keyof PlasmicValueProp__ArgsType;
export const PlasmicValueProp__ArgProps = new Array<ArgPropType>(
  "description",
  "icon",
  "title"
);

export type PlasmicValueProp__OverridesType = {
  root?: p.Flex<"div">;
  iconContainer?: p.Flex<"div">;
  contentContainer?: p.Flex<"div">;
};

export interface DefaultValuePropProps {
  description?: React.ReactNode;
  icon?: React.ReactNode;
  title?: React.ReactNode;
  flatIcon?: SingleBooleanChoiceArg<"flatIcon">;
  vertical?: SingleBooleanChoiceArg<"vertical">;
  card?: SingleBooleanChoiceArg<"card">;
  noTitle?: SingleBooleanChoiceArg<"noTitle">;
  darkBackground?: SingleBooleanChoiceArg<"darkBackground">;
  className?: string;
}

function PlasmicValueProp__RenderFunc(props: {
  variants: PlasmicValueProp__VariantsArgs;
  args: PlasmicValueProp__ArgsType;
  overrides: PlasmicValueProp__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootcard]: hasVariant(variants, "card", "card"),
          [sty.rootflatIcon]: hasVariant(variants, "flatIcon", "flatIcon"),
          [sty.rootnoTitle]: hasVariant(variants, "noTitle", "noTitle"),
          [sty.rootvertical]: hasVariant(variants, "vertical", "vertical"),
          [sty.rootvertical_card]:
            hasVariant(variants, "card", "card") &&
            hasVariant(variants, "vertical", "vertical")
        }
      )}
    >
      <div
        data-plasmic-name={"iconContainer"}
        data-plasmic-override={overrides.iconContainer}
        className={classNames(projectcss.all, sty.iconContainer, {
          [sty.iconContainercard]: hasVariant(variants, "card", "card"),
          [sty.iconContainerflatIcon]: hasVariant(
            variants,
            "flatIcon",
            "flatIcon"
          ),
          [sty.iconContainervertical]: hasVariant(
            variants,
            "vertical",
            "vertical"
          ),
          [sty.iconContainervertical_card]:
            hasVariant(variants, "card", "card") &&
            hasVariant(variants, "vertical", "vertical")
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__mOx7A)}
              displayHeight={"56px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"none" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"56px" as const}
              src={
                "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/red-apple_1f34e.png" as const
              }
            />
          ),

          value: args.icon
        })}
      </div>

      <p.Stack
        as={"div"}
        data-plasmic-name={"contentContainer"}
        data-plasmic-override={overrides.contentContainer}
        hasGap={true}
        className={classNames(projectcss.all, sty.contentContainer, {
          [sty.contentContainerflatIcon]: hasVariant(
            variants,
            "flatIcon",
            "flatIcon"
          ),
          [sty.contentContainernoTitle]: hasVariant(
            variants,
            "noTitle",
            "noTitle"
          )
        })}
      >
        {(hasVariant(variants, "noTitle", "noTitle") ? false : true)
          ? p.renderPlasmicSlot({
              defaultContents: "Label",
              value: args.title,
              className: classNames(sty.slotTargetTitle, {
                [sty.slotTargetTitledarkBackground]: hasVariant(
                  variants,
                  "darkBackground",
                  "darkBackground"
                ),
                [sty.slotTargetTitlenoTitle]: hasVariant(
                  variants,
                  "noTitle",
                  "noTitle"
                )
              })
            })
          : null}
        {p.renderPlasmicSlot({
          defaultContents:
            "Porttitor feugiat a scelerisque nullam parturient vestibulum tempor a litora suscipit arcu potenti varius venenatis venenatis dapibus fames adipiscing in in taciti.",
          value: args.description,
          className: classNames(sty.slotTargetDescription, {
            [sty.slotTargetDescriptioncard]: hasVariant(
              variants,
              "card",
              "card"
            ),
            [sty.slotTargetDescriptiondarkBackground]: hasVariant(
              variants,
              "darkBackground",
              "darkBackground"
            ),
            [sty.slotTargetDescriptionnoTitle]: hasVariant(
              variants,
              "noTitle",
              "noTitle"
            )
          })
        })}
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "iconContainer", "contentContainer"],
  iconContainer: ["iconContainer"],
  contentContainer: ["contentContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  iconContainer: "div";
  contentContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValueProp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicValueProp__VariantsArgs;
    args?: PlasmicValueProp__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicValueProp__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicValueProp__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicValueProp__ArgProps,
          internalVariantPropNames: PlasmicValueProp__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicValueProp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValueProp";
  } else {
    func.displayName = `PlasmicValueProp.${nodeName}`;
  }
  return func;
}

export const PlasmicValueProp = Object.assign(
  // Top-level PlasmicValueProp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iconContainer: makeNodeComponent("iconContainer"),
    contentContainer: makeNodeComponent("contentContainer"),

    // Metadata about props expected for PlasmicValueProp
    internalVariantProps: PlasmicValueProp__VariantProps,
    internalArgProps: PlasmicValueProp__ArgProps
  }
);

export default PlasmicValueProp;
/* prettier-ignore-end */
