// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sjVjhDwAwAnzPPjTJm6wuM
// Component: AYM_aE6u_bfmbh
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: r_jYinXni53Wi6/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent
import Button from "../../Button"; // plasmic-import: P-H-3Rnl6IFnul/component
import Section from "../../Section"; // plasmic-import: oWYT0gs3X9I9Bn/component
import ValueProp from "../../ValueProp"; // plasmic-import: 7mTzTuLk_-7aUm/component
import Banner from "../../Banner"; // plasmic-import: 3D6_6FjgJJmjcZ/component
import PriceCard from "../../PriceCard"; // plasmic-import: 7hmLk_KxVSEe3t/component
import FathymFooter from "../../FathymFooter"; // plasmic-import: vPms2ampwPsR50/component

import { useScreenVariants as useScreenVariantspCqVwGHbhXBxmj } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: pCQVwGHbhXBxmj/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_azure_landing_page_project.module.css"; // plasmic-import: sjVjhDwAwAnzPPjTJm6wuM/projectcss
import sty from "./PlasmicLandingPagesSvelte2.module.css"; // plasmic-import: AYM_aE6u_bfmbh/css

import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: EI-h-RaqbBFLXd/icon
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: 1iS8qc8aNS9fy4/icon
import HammerIcon from "./icons/PlasmicIcon__Hammer"; // plasmic-import: Je5DF38UZGEgnB/icon
import TargetIcon from "./icons/PlasmicIcon__Target"; // plasmic-import: sPCmogus4ouA9k/icon
import FastIcon from "./icons/PlasmicIcon__Fast"; // plasmic-import: H-iJq0bUoQ97DL/icon
import StrongIcon from "./icons/PlasmicIcon__Strong"; // plasmic-import: 1JkRJedt6l5M0H/icon

export type PlasmicLandingPagesSvelte2__VariantMembers = {};

export type PlasmicLandingPagesSvelte2__VariantsArgs = {};
type VariantPropType = keyof PlasmicLandingPagesSvelte2__VariantsArgs;
export const PlasmicLandingPagesSvelte2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLandingPagesSvelte2__ArgsType = {};
type ArgPropType = keyof PlasmicLandingPagesSvelte2__ArgsType;
export const PlasmicLandingPagesSvelte2__ArgProps = new Array<ArgPropType>();

export type PlasmicLandingPagesSvelte2__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  foreground?: p.Flex<"div">;
  youTube?: p.Flex<typeof YouTube>;
  foreground2?: p.Flex<"div">;
  valuePropsSection?: p.Flex<typeof Section>;
  banner?: p.Flex<typeof Banner>;
  section?: p.Flex<"section">;
  foreground3?: p.Flex<"div">;
  fathymFooter?: p.Flex<typeof FathymFooter>;
};

export interface DefaultLandingPagesSvelte2Props {}

function PlasmicLandingPagesSvelte2__RenderFunc(props: {
  variants: PlasmicLandingPagesSvelte2__VariantsArgs;
  args: PlasmicLandingPagesSvelte2__ArgsType;
  overrides: PlasmicLandingPagesSvelte2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspCqVwGHbhXBxmj()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">
          {"Fathym - Svelte Development & Deployments in record time"}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={"Fathym - Svelte Development & Deployments in record time"}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={"Fathym - Svelte Development & Deployments in record time"}
        />
        <meta
          key="description"
          name="description"
          content={
            "Deploy and host your Svelte project on Fathym in just a few clicks. "
          }
        />
        <meta
          key="og:description"
          property="og:description"
          content={
            "Deploy and host your Svelte project on Fathym in just a few clicks. "
          }
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={
            "Deploy and host your Svelte project on Fathym in just a few clicks. "
          }
        />
        <meta
          key="og:image"
          property="og:image"
          content={
            "https://site-assets.plasmic.app/2c55fdac029a023cd64910df84bd6305.jpg"
          }
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={
            "https://site-assets.plasmic.app/2c55fdac029a023cd64910df84bd6305.jpg"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__oogor)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground"}
              data-plasmic-override={overrides.foreground}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground)}
            >
              <Reveal
                className={classNames("__wab_instance", sty.reveal__xiDxd)}
                triggerOnce={false}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xPz38
                  )}
                >
                  {"Svelte Deployments\nwith Fathym"}
                </div>
              </Reveal>

              <Reveal
                className={classNames("__wab_instance", sty.reveal__g3IGu)}
                triggerOnce={false}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nxVas
                  )}
                >
                  {"Create, build, and deploy your next Svelte app with Fathym"}
                </div>
              </Reveal>
            </p.Stack>

            <Reveal
              className={classNames("__wab_instance", sty.reveal__yzFwE)}
              effect={"bounce" as const}
              triggerOnce={false}
            >
              <YouTube
                data-plasmic-name={"youTube"}
                data-plasmic-override={overrides.youTube}
                className={classNames("__wab_instance", sty.youTube)}
                videoId={"gOo_lTcJo7Y" as const}
              />
            </Reveal>

            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.columns__i1Uh)}>
                <div className={classNames(projectcss.all, sty.column__hFlph)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__cN37M)}
                    color={"blue" as const}
                    link={"/dashboard/create-project/recipe/svelte" as const}
                  >
                    {"Get Started for Free"}
                  </Button>
                </div>

                <div className={classNames(projectcss.all, sty.column__fef5K)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___1SvI1
                    )}
                    component={Link}
                    href={"/docs/guides/deploying/frameworks/svelte" as const}
                    platform={"nextjs"}
                  >
                    {"Learn more >"}
                  </p.PlasmicLink>
                </div>
              </div>
            </p.Stack>

            <Section
              data-plasmic-name={"valuePropsSection"}
              data-plasmic-override={overrides.valuePropsSection}
              className={classNames("__wab_instance", sty.valuePropsSection)}
            >
              <Reveal
                className={classNames("__wab_instance", sty.reveal___8Tz6T)}
                direction={"down" as const}
                triggerOnce={false}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zhImr)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__smfcr)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__de2I
                      )}
                    >
                      {"See how Svelte Compares"}
                    </h2>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l9Oj
                    )}
                  >
                    {
                      "Looking for the right framework for your next Jamstack example, tutorial or project?  Deploy Svelte alongside any number of additional frameworks, get a feel for the development experience, and see how they perform.  Deploy your Svelte app free with Fathym's micro frontend framework."
                    }
                  </div>
                </p.Stack>
              </Reveal>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kO3Mc)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nuOoY)}
                >
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__mTYde)}
                    direction={"up" as const}
                    triggerOnce={false}
                  >
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp__iPo9A
                      )}
                      description={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rpsHr
                            )}
                          >
                            {
                              "React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components."
                            }
                          </div>

                          <p.PlasmicLink
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__tzCcK
                            )}
                            component={Link}
                            href={"/" as const}
                            platform={"nextjs"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mglrP
                              )}
                            >
                              {"React Deployments >"}
                            </div>
                          </p.PlasmicLink>

                          {true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__orvOt
                              )}
                              link={"/react" as const}
                            >
                              {null}
                            </Button>
                          ) : null}
                        </React.Fragment>
                      }
                      flatIcon={true}
                      icon={
                        <CheckIcon
                          className={classNames(projectcss.all, sty.svg__ad6Gj)}
                          role={"img"}
                        />
                      }
                      title={"Svelte vs React"}
                    />
                  </Reveal>

                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__kHsJz)}
                    direction={"up" as const}
                    triggerOnce={false}
                  >
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp___9HRv
                      )}
                      description={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kgEyx
                            )}
                          >
                            {
                              "The progressive javascript framework.  Already know HTML, CSS and JavaScript? Read the guide and start deploying VueJS apps in no time!               \n"
                            }
                          </div>

                          <p.PlasmicLink
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__bywyd
                            )}
                            component={Link}
                            platform={"nextjs"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___759G8
                              )}
                            >
                              {"Vue Deployments >"}
                            </div>
                          </p.PlasmicLink>

                          {true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__jc7Vf
                              )}
                              link={"/vue" as const}
                            >
                              {null}
                            </Button>
                          ) : null}
                        </React.Fragment>
                      }
                      flatIcon={true}
                      icon={
                        <CheckIcon
                          className={classNames(projectcss.all, sty.svg__tsuxP)}
                          role={"img"}
                        />
                      }
                      title={"Svelte vs VueJS"}
                    />
                  </Reveal>

                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__joGpj)}
                    direction={"up" as const}
                    triggerOnce={false}
                  >
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp__da2S
                      )}
                      description={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pvGbb
                            )}
                          >
                            {
                              "Learn one way to build applications with Angular and reuse your code and abilities to build apps for any deployment target. Deploy your Angular app now."
                            }
                          </div>

                          <p.PlasmicLink
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link___1Pczu
                            )}
                            component={Link}
                            platform={"nextjs"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vVgMu
                              )}
                            >
                              {"Angular Deployments >"}
                            </div>
                          </p.PlasmicLink>

                          {true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__tcixz
                              )}
                              link={"/angular" as const}
                            >
                              {null}
                            </Button>
                          ) : null}
                        </React.Fragment>
                      }
                      flatIcon={true}
                      icon={
                        <CheckIcon
                          className={classNames(projectcss.all, sty.svg__bGKlg)}
                          role={"img"}
                        />
                      }
                      title={"Svelte vs Angular"}
                    />
                  </Reveal>
                </p.Stack>
              </p.Stack>
            </Section>

            <Banner
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              className={classNames("__wab_instance", sty.banner)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yefA
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Svelte Example Tutorial"
                      : "svelte Example Tutorial"}
                  </div>

                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__oVkx3)}
                    direction={"right" as const}
                    triggerOnce={false}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pkD78
                      )}
                    >
                      {"Do it Yourself"}
                    </div>
                  </Reveal>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ciVwm
                    )}
                  >
                    {
                      "Get started now and deploy your Svelte app to production following the simple deployment guide. Have your Svelte micro frontend hosted on your domain in minutes."
                    }
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.columns__lu3Pu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___1EOxr)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__rpM9Q
                        )}
                        color={"blue" as const}
                        link={
                          "/dashboard/create-project/recipe/svelte" as const
                        }
                      >
                        {"Get Started for Free"}
                      </Button>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__hWyXc)}
                    >
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link___2MNx7
                        )}
                        component={Link}
                        href={
                          "/docs/guides/deploying/frameworks/svelte" as const
                        }
                        platform={"nextjs"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7Pb1F
                          )}
                        >
                          {"Read Documentation >"}
                        </div>
                      </p.PlasmicLink>

                      {true ? (
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__uhwAs
                          )}
                          link={
                            "/docs/guides/deploying/frameworks/svelte" as const
                          }
                        >
                          {null}
                        </Button>
                      ) : null}
                    </div>
                  </div>
                </React.Fragment>
              }
            />
          </p.Stack>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground3"}
              data-plasmic-override={overrides.foreground3}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__i1KSj)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__pcj9O)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__bIi54)}
                    direction={"right" as const}
                    triggerOnce={false}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___8AnX
                      )}
                    >
                      {"Why deploy Svelte?"}
                    </h2>
                  </Reveal>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o289
                  )}
                >
                  {
                    "Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app.\n\nInstead of using techniques like virtual DOM diffing, Svelte writes code that surgically updates the DOM when the state of your app changes."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tkcey)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__eHUd2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__uPlte)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__a0W8
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wLCvh
                            )}
                          >
                            {
                              "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                            }
                          </div>
                        }
                        icon={
                          <HammerIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fmSg
                            )}
                            role={"img"}
                          />
                        }
                        title={"Harder"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__kjpMr)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__msjLu
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__k4UxL
                            )}
                          >
                            {
                              "Consequat scelerisque a eros taciti nisl a sodales."
                            }
                          </div>
                        }
                        icon={
                          <TargetIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__iPfmP
                            )}
                            role={"img"}
                          />
                        }
                        title={"Better"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__kvGsH)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__pmhki
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qWhh2
                            )}
                          >
                            {
                              "Varius ad malesuada ullamcorper cursus scelerisque a a."
                            }
                          </div>
                        }
                        icon={
                          <FastIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___33L3L
                            )}
                            role={"img"}
                          />
                        }
                        title={"Faster"}
                        vertical={true}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__lcg53)}
                    >
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__hMeLy
                        )}
                        darkBackground={true}
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sfXlG
                            )}
                          >
                            {
                              "Ut eu nam nostra taciti congue adipiscing curabitur."
                            }
                          </div>
                        }
                        icon={
                          <StrongIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__m7JaB
                            )}
                            role={"img"}
                          />
                        }
                        title={"Stronger"}
                        vertical={true}
                      />
                    </div>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <div className={classNames(projectcss.all, sty.freeBox__dmRBo)}>
                <Button
                  className={classNames("__wab_instance", sty.button__zf722)}
                  color={"blue" as const}
                  link={"/dashboard/create-project/recipe/svelte" as const}
                >
                  {"Get Started for Free"}
                </Button>

                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__e8ITb
                  )}
                  component={Link}
                  href={"/docs/guides/deploying/frameworks/svelte" as const}
                  platform={"nextjs"}
                >
                  {"Learn more >"}
                </p.PlasmicLink>
              </div>

              {true ? (
                <div className={classNames(projectcss.all, sty.columns__fNcjt)}>
                  <div
                    className={classNames(projectcss.all, sty.column__npKR)}
                  />

                  <div
                    className={classNames(projectcss.all, sty.column__ttyX0)}
                  />
                </div>
              ) : null}
            </p.Stack>
          </section>

          {true ? (
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___9Lw)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lGy1M)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bab4C)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iwKfo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8Ym3T
                      )}
                    >
                      {"Pricing plans"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tnMSk
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___86OvT)}
                >
                  <PriceCard
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__zQrew
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__bQSo7
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__eQspi
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___1W8Nz
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___4GKe8
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"0"}
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ziNPs
                        )}
                      >
                        {"Buy Pro"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__yMQb
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__px6A
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__qk1Xv
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__a5Gpi
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__eAHnL
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__yXoom
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__yL2G
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"8"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qqk1Q
                        )}
                      >
                        {"Pro"}
                      </div>
                    }
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ljjE0
                        )}
                      >
                        {"Buy Team"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__zNa98
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__obLJs
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__z9XDa
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__lQylr
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ftmSf
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__pBnk9
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__k4Vxi
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__ov97W
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hAjcu
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"16"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xReSk
                        )}
                      >
                        {"Team"}
                      </div>
                    }
                  />

                  <PriceCard
                    action={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zhk93
                        )}
                      >
                        {"Contact us"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__wKuYf
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___4563Z
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hA4D3
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__k63La
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__mvBhU
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__vtMyj
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xr4Vs
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__gBhak
                          )}
                          description={"Nulla odio mauris."}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__mg0IF
                              )}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"?"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bsbtl
                        )}
                      >
                        {"Enterprise"}
                      </div>
                    }
                    primary={true}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}

          <FathymFooter
            data-plasmic-name={"fathymFooter"}
            data-plasmic-override={overrides.fathymFooter}
            className={classNames("__wab_instance", sty.fathymFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "foreground",
    "youTube",
    "foreground2",
    "valuePropsSection",
    "banner",
    "section",
    "foreground3",
    "fathymFooter"
  ],
  navbar: ["navbar"],
  foreground: ["foreground"],
  youTube: ["youTube"],
  foreground2: ["foreground2"],
  valuePropsSection: ["valuePropsSection"],
  banner: ["banner"],
  section: ["section", "foreground3"],
  foreground3: ["foreground3"],
  fathymFooter: ["fathymFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  foreground: "div";
  youTube: typeof YouTube;
  foreground2: "div";
  valuePropsSection: typeof Section;
  banner: typeof Banner;
  section: "section";
  foreground3: "div";
  fathymFooter: typeof FathymFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLandingPagesSvelte2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLandingPagesSvelte2__VariantsArgs;
    args?: PlasmicLandingPagesSvelte2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLandingPagesSvelte2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLandingPagesSvelte2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandingPagesSvelte2__ArgProps,
          internalVariantPropNames: PlasmicLandingPagesSvelte2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandingPagesSvelte2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandingPagesSvelte2";
  } else {
    func.displayName = `PlasmicLandingPagesSvelte2.${nodeName}`;
  }
  return func;
}

export const PlasmicLandingPagesSvelte2 = Object.assign(
  // Top-level PlasmicLandingPagesSvelte2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    foreground: makeNodeComponent("foreground"),
    youTube: makeNodeComponent("youTube"),
    foreground2: makeNodeComponent("foreground2"),
    valuePropsSection: makeNodeComponent("valuePropsSection"),
    banner: makeNodeComponent("banner"),
    section: makeNodeComponent("section"),
    foreground3: makeNodeComponent("foreground3"),
    fathymFooter: makeNodeComponent("fathymFooter"),

    // Metadata about props expected for PlasmicLandingPagesSvelte2
    internalVariantProps: PlasmicLandingPagesSvelte2__VariantProps,
    internalArgProps: PlasmicLandingPagesSvelte2__ArgProps
  }
);

export default PlasmicLandingPagesSvelte2;
/* prettier-ignore-end */
